-- GENERATED by tools/gen-post-seed.mjs from content/blog/*.md — do not edit by hand.
-- The three posts the blog launched with, moved out of static HTML and into
-- D1 so they can be edited in the admin like any other post.
-- OR IGNORE: re-running the deploy must never undo an edit made in the admin.

INSERT OR IGNORE INTO posts (slug, title, description, body, published, created_at, updated_at)
VALUES ('grief-does-not-follow-a-timeline', 'Grief doesn''t follow a timeline', 'On the year after a death, the things people say that don''t help, the goodbye you never got to say, and why missing someone forever is not a failure to heal.', 'Somewhere between the funeral and the third month, the messages stop arriving and everyone assumes you''re through the worst of it. Usually that''s when it actually starts.

## The five stages were never a schedule

Denial, anger, bargaining, depression, acceptance — almost everyone has heard the list, and almost everyone has quietly worried about being on the wrong stage. Elisabeth Kübler-Ross drew it from watching dying patients, not the bereaved, and she later said plainly that it was never meant as a sequence to be completed.

Real grief doesn''t queue up. You can be furious and numb in the same hour, fine on the anniversary and destroyed by an ordinary Tuesday because a stranger walked with the same gait. There''s no stage you''re failing to reach.

## The second wave, when everyone else has moved on

In the first weeks there''s a strange amount of activity: arrangements, relatives, people bringing food. It keeps you upright and it also keeps the loss slightly unreal.

Then it stops. Everyone returns to their lives — correctly, because it isn''t their loss — and you''re left in a quiet house with the actual fact of it. This is the point where most people start pretending. You say "I''m doing better" because you can hear how tired the question has made everyone, and then you carry the real thing alone.

If you''re there right now: nothing has gone wrong with you. Month four is routinely harder than week one, and almost nobody warns you.

## The goodbye you didn''t get to say

A particular kind of pain belongs to the words that never got said. You weren''t there. You were there but they weren''t conscious. The last conversation was about something trivial, or it was an argument. You said "talk tomorrow" and there wasn''t one.

You can''t fix that by finding the right thing to think. But the words don''t have to stay inside you either. People write the letter anyway — the one that can''t be sent — and it helps far more than it has any right to. Say what you''d have said. Tell them the thing they didn''t know. It isn''t pretending they can hear you; it''s finishing the sentence you were left holding.

## Things people say, and what''s wrong with them

- **"They''re in a better place."** Maybe. They''re not in this one, which is the problem.
- **"At least they didn''t suffer."** "At least" has never once made anyone feel less alone.
- **"Everything happens for a reason."** Some things don''t, and being asked to find the reason is extra work handed to the person with the least energy in the room.
- **"You need to move on."** Move on to where? People aren''t stages of a project.
- **"Be strong for your family."** This is how people end up grieving in the bathroom with the tap running.

Most of these come from people who care and can''t bear your pain. That''s worth remembering when you decide how much to forgive. It''s also why so many people end up saying the true version to a stranger instead.

## You don''t get over it. It changes shape

The honest version is that grief doesn''t shrink so much as your life grows around it. The loss stays the size it always was. Around it, slowly, there''s more — ordinary days, new people, things that are genuinely funny again. The proportion changes, not the thing itself.

So the waves that arrive years later aren''t a relapse and aren''t a sign you never dealt with it. They''re the same size wave hitting a bigger shore.

> Love never truly disappears.

That''s not a consolation slogan. It''s the practical reason grief lasts: it is exactly as durable as the attachment underneath it, and you would not trade away the attachment to be rid of the grief.

## When to get real help

Grief is not a disorder. But if months in you can''t work, can''t eat, can''t get out of bed, or the thought of joining them starts to feel like a plan rather than a wish — that''s not weakness or failure, it''s the point where grief needs a professional, the same way a broken bone does.

---

If you''re thinking about ending your life, please talk to someone tonight. Mainland China: **12356**. US and Canada: **988**. UK and Ireland: **116 123**. Elsewhere, [findahelpline.com](https://findahelpline.com).', 1, 1786006800000, 1786006800000);

INSERT OR IGNORE INTO posts (slug, title, description, body, published, created_at, updated_at)
VALUES ('how-to-get-through-the-night-after-a-breakup', 'How to get through the night after a breakup', 'Not how to move on. How to get through tonight — the 3 a.m. hours after a breakup, when the missing them is loudest and nothing sensible helps yet.', 'Everything written about heartbreak is about moving on. This isn''t. Moving on is a question for a month from now. Tonight the only question is how to get from here to morning.

## Why nights are so much worse

It isn''t your imagination. During the day you have tasks, noise, other people''s faces — a hundred small things standing between you and the thought. At night all of it goes quiet at once, you''re tired enough that your defences are down, and the thought gets the whole room to itself.

Add to that the fact that the night used to be theirs. The last message of the day, the call before sleep, the shape of someone next to you. The hours you''re most alone are precisely the hours that used to be least alone. So the missing isn''t a sign you''re failing to cope. It''s arriving exactly when it always would.

## Things that actually help at 3 a.m.

None of these fix anything. They''re just what tends to work when it''s dark and you''re not going to sleep for a while.

- **Get out of the bed you''re spiralling in.** Sit up, go to another room, put a light on. Lying still in the dark is the single most efficient way to think in circles.
- **Do something with your hands and nothing with your judgement.** Wash a dish, fold clothes, make tea you don''t drink. Small physical tasks occupy the part of the mind that''s been running the same argument for two hours.
- **Write the message you want to send — and don''t send it.** Put it in your notes app, write it out completely, be as unfiltered as you like. Most of the urge is the need to say it, not the need for them to read it. Reread it tomorrow at noon, when you''ll be a different person.
- **Cold water on your face and wrists.** It sounds like nothing. It genuinely takes the edge off a body that''s stuck in alarm.
- **Tell someone, even a stranger.** Not to get advice. Just so the thing is outside of you, in words, being read by someone. It works even when it shouldn''t.
- **Set the bar at getting to morning.** Not sleeping. Not being okay. Not "handling it well". Just morning.

## What not to do to yourself tonight

- **Don''t check their profile.** You know this. You''ll do it anyway. If you can, hand your phone to a friend or put the app in a folder you''d have to think to open. Every check restarts the clock.
- **Don''t run the highlight reel.** At 3 a.m. memory only serves the best moments and the worst ones. Neither is the relationship you actually had.
- **Don''t audit yourself.** Whatever the list of things you should have said or done differently, tonight is the worst possible time to write it. You are not conducting an honest review — you are looking for reasons to hurt.
- **Be careful with alcohol.** It shortens the evening and lengthens the 4 a.m.

## Missing them is not the same as needing them back

This is the part almost nobody is told. You can know with complete clarity that the relationship was wrong, that you ended it for good reasons, that you''d never go back — and still be flattened by missing them.

Missing someone is a habit of attention. For a long time, everything that happened to you was routed towards one person. That routing doesn''t switch off because the reasoning changed; it wears down slowly, by not being used. Grief for a relationship isn''t proof you made a mistake. It''s proof it was real.

## What tomorrow actually looks like

Not linear. You''ll have three decent days and then a song in a shop will take you apart. Recovery from heartbreak isn''t a slope, it''s a series of ambushes that get further apart. When one hits after a good week, it isn''t a relapse. The distance between them is the real measurement.

---

If tonight is worse than sad — if you''re thinking about hurting yourself — please call someone now. Mainland China: **12356**. US and Canada: **988**. UK and Ireland: **116 123**. Elsewhere, [findahelpline.com](https://findahelpline.com). You deserve an actual voice tonight, not a page.', 1, 1786006800000, 1786006800000);

INSERT OR IGNORE INTO posts (slug, title, description, body, published, created_at, updated_at)
VALUES ('why-it-is-easier-to-tell-a-stranger', 'Why it''s easier to tell a stranger than someone who loves you', 'Why people confess to strangers on trains, in taxis, and online — and why telling someone who has no stake in your life can be the safest place to start.', 'People say things on night trains they have never said at home. Taxi drivers hear confessions. So do hairdressers, nurses on a night shift, and the person on the next barstool. It isn''t that we trust strangers more. It''s that strangers cost less.

## The people who love you have to live with your answer

When you tell a close friend that you''re not okay, you hand them something they now have to carry. They''ll worry. They''ll check in. They''ll remember it the next time you laugh and wonder whether the laugh was real.

Most people can feel that weight in advance, and they decide — usually without ever putting it into words — that it''s kinder to say nothing. "I don''t want to burden them" is the single most common reason people stay silent about the thing that''s hurting them most.

A stranger has no such stake. They can hear the worst week of your life, say something true about it, and go back to their own evening. Nothing gets heavier for them. That''s not coldness — it''s exactly what makes the space around them safe to speak in.

## They didn''t know the old version of you

The second cost is your record. The people who know you have a picture of who you are: the capable one, the funny one, the one who holds everyone else together. Saying "I''m falling apart" doesn''t just deliver information. It edits the picture, permanently.

Psychologists have called this the *stranger on the train* effect: we disclose more to people we don''t expect to see again, because there''s no future relationship for the disclosure to damage. A stranger meets only the version of you that exists right now. Nothing has to be revised, because nothing was assumed.

## Saying it out loud is doing something, even if nobody fixes it

There''s a persistent belief that talking about a problem is pointless unless it produces a solution. In practice, the opposite is closer to true. Putting a feeling into words changes how it sits in you. The vague, roaring dread becomes a sentence — and a sentence has edges, and edges can be looked at.

That''s why people so often say "I don''t know why I''m telling you this" and then feel better afterwards anyway. The relief wasn''t in the advice. It was in the telling.

## Being answered by someone with no reason to answer

There''s a second thing, though, and it matters more than the confessing.

When a friend comforts you, part of you can always discount it: they have to say that, they love you. When a total stranger reads what you wrote at 3 a.m. and takes the time to answer — someone who gains nothing, who you will never meet, who owes you nothing at all — the kindness is impossible to argue with. It has no obligation behind it. It''s the clearest evidence there is that the world contains people who will stop for you.

## What this isn''t

Talking to strangers is a place to start, not a place to live. It can carry you through a night. It can loosen something enough that you can finally say it to someone who knows you, or to a therapist. It isn''t a replacement for either, and it can''t help at all if you''re in danger right now — for that, please call a crisis line in your country tonight.

But if you''ve been holding something for months because there''s no one you can hand it to without changing how they see you: a stranger is a real answer to that problem. Not a lesser one. Just a different one.', 1, 1786006800000, 1786006800000);
