-- SPLIT — see 0018 through 0022. This file is intentionally empty now.
--
-- It used to hold four ALTER TABLE statements and two indexes, and that is
-- what broke the live site: D1 executes a --file as ONE unit and rolls the
-- whole thing back if any statement in it fails. So one failure did not cost
-- one column, it cost all four — and the deploy still reported success,
-- because the workflow only inspected output when wrangler exited non-zero.
--
-- The site then ran new code against an old schema: the sky still listed
-- whispers (that query touches no new column), while publishing and opening
-- one both answered 500. "New features missing and old features broken" is
-- exactly the shape that produces.
--
-- One statement per file from now on. A file that fails then costs exactly
-- what it contains, the "duplicate column name" tolerance in the deploy
-- applies per statement, and the schema check that follows the migrations
-- turns a silent half-applied database into a failed deploy.
SELECT 1;
